name: roseapple-pi-kernel
version: 3.10.37
summary: A roseapple kernel built from source
description: This is the reference kernel from xapp-le branch Ubuntu-Snappy-Core
type: kernel

parts:
    kernel:
        plugin: kernel
        source: .
        source-branch: Ubuntu-Snappy-Core
        source-type: git
        kdefconfig: [actduino_bubble_gum_linux_defconfig, snappy/generic.config, snappy/security.config, snappy/systemd.config, snappy/snappy.config, snappy/containers.config]
        kconfigs:
            - CONFIG_LOCALVERSION="-roseapple"
            - CONFIG_DEBUG_INFO=n
            - CONFIG_SQUASHFS=m
        kernel-initrd-modules:
            - squashfs
        kernel-image-target: zImage
        kernel-device-trees:
            - actduino_bubble_gum_sdboot_linux
        build-packages: [bc, kmod, cpio]
